## Experiment No 9
## Study of Pandas library
## Name: Atharva Jadhav
## PRN: 25070123027
## Batch:ENTC A2

In [ ]:
# Introduction to Pandas
# Pandas : Panel Data

In [2]:
import pandas as pd
s=pd.Series([1,2,3,4,5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [5]:
# Creating a DataFrame
data={
    "Name":["A","B","D"],
    "Marks":[78,90,88]
}
df=pd.DataFrame(data)
df

  Name  Marks
0    A     78
1    B     90
2    D     88

In [7]:
# Head gives first 5 entries and Tail gives last 5 entries
df.head()
df.tail()

  Name  Marks
0    A     78
1    B     90
2    D     88

In [10]:
# Find the structure of the DatFrame
df.shape

(3, 2)

In [11]:
# Dimenstions
df.ndim

2

In [12]:
# Size (No of total values are there)
df.size

6

In [13]:
# Display Column Names
df.columns

Index(['Name', 'Marks'], dtype='object')

In [14]:
# Check DataTypes of each Column
df.dtypes

Name     object
Marks     int64
dtype: object

In [15]:
# Access Individual Column
df["Name"]

0    A
1    B
2    D
Name: Name, dtype: object

In [17]:
# Access Specific rows
df.loc[1]

Name      B
Marks    90
Name: 1, dtype: object

In [25]:
# Add a New Column
df["Grade"]=["First Class","Distinction","Second Class"]
df

  Name  Marks         Grade
0    A     88   First Class
1    B     90   Distinction
2    D     88  Second Class

In [26]:
# Update Data in DataFrame
# Change marks of student A to 88
df.loc[0,"Marks"]=88
df

  Name  Marks         Grade
0    A     88   First Class
1    B     90   Distinction
2    D     88  Second Class

In [27]:
# Delete a column
df.drop("Grade",axis=1,inplace=True)
df

  Name  Marks
0    A     88
1    B     90
2    D     88

In [28]:
# Perform Basic Statistical Analysis
mean1=df["Marks"].mean()
mean1

np.float64(88.66666666666667)

In [29]:
# To find the minimum and maximum value of marks
min1=df["Marks"].min()
max1=df["Marks"].max()
print(min1,max1)

88 90

In [30]:
# Apply a condition (Filtering)
# Display students scoring more than 89
df[df["Marks"]>89]

  Name  Marks
1    B     90